include(CheckIncludeFile)

#message("CMAKE_REQUIRED_INCLUDES: ${CMAKE_REQUIRED_INCLUDES}")

CHECK_INCLUDE_FILE(stddef.h HAS_STDDEF_H)
CHECK_INCLUDE_FILE(stdint.h HAS_STDINT_H)
CHECK_INCLUDE_FILE(stdarg.h HAS_STDARG_H)
